input:
  compute_dice:   True                      # Whether to compute dice scores. Requires scans to have a label/ground_truth. 
  mode:           "single"                  # Optional. Whether to load multiple scans from a list, or to infer on a single scan. Either 'single' or 'multi'.
  multi_scan:                       
    scan_list:    "data/multi_example.json" # Loads a json list of scans to perform inference on. 
  single_scan:                              # For a single scan, define the locations of all .nii.gz modalities relative to data_dir. 
    ground_truth: "UCSF-PDGM-0444_tumor_segmentation.nii.gz" # Only required if compute_dice is True. 
    flair:        "UCSF-PDGM-0444_FLAIR_bias.nii.gz"
    t1c:          "UCSF-PDGM-0444_T1c_bias.nii.gz"
    t1:           "UCSF-PDGM-0444_T1.nii.gz"
    t2:           "UCSF-PDGM-0444_T2_bias.nii.gz"
  data_dir:       "data/"                   # The directory where input scans are located. 

output:                                     # File path to the output inference. 
  file_path:      "out/segmentation_mask.nii.gz"

model:                                      # AWS S3 details for retrieving the model. 
  bucket:         "theta-trained-models"
  key:            "model.ckpt"
  region:         "us-east-1"